name: Deploy to Snowflake

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL CLI
        run: |
          pipx ensurepath
          pipx install snowflake-cli-labs

      - name: Run deploy.sql using Snowflake CLI
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_ROLE: ACCOUNTADMIN
          SNOWFLAKE_WAREHOUSE: DEVOPS_WH
          SNOWFLAKE_DATABASE: DEVOPS_DB
          SNOWFLAKE_SCHEMA: COMMON
          
        run: |
          snowsql config init
          snow connection add github-ci --account name $LY85053 --username $RAMA --password $Magmutual@2025
          snow sql -q "USE ROLE ACCOUNTADMIN; USE WAREHOUSE DEVOPS_WH; USE DATABASE DEVOPS_DB; USE SCHEMA COMMON;"
          snow sql -f snowflake-deploy.sql
          snow sql -c github-ci -f snowflake-deploy.sql
          
