name: Deploy to Snowflake

on:
  push:
    branches:
      - main
jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL using official GitHub Action
        uses: snowflakedb/setup-snowflake-cli@v1

      - name: Run deploy.sql using Snowflake CLI
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          SNOWSQL_ROLE: ACCOUNTADMIN
          SNOWFLAKE_WAREHOUSE: DEVOPS_WH
          SNOWFLAKE_DATABASE: DEVOPS_DB
          SNOWFLAKE_SCHEMA: COMMON
          
        run: |
          snowsql -f snowflake-deploy.yml
