name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # adjust if you use a different branch

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: '3.6.0'  # optional, omit for latest

      - name: Configure Snowflake CLI connection profile
        env:
          ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          USER: ${{ secrets.SNOWSQL_USER }}
          PASSWORD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          mkdir -p ~/.snowflake
          cat > ~/.snowflake/config.toml <<EOF
          [connections.default]
          account = "${ACCOUNT}"
          user = "${USER}"
          password = "${PASSWORD}"
          role = "ACCOUNTADMIN"
          warehouse = "DEVOPS_WH"
          database = "DEVOPS_DB"
          schema = "COMMON"
          EOF
          chmod 0600 ~/.snowflake/config.toml  # Secure file permissions

      - name: Run SQL using Snowflake CLI
        run: |
          snow sql --filename snowflake-deploy.sql --connection default
          
