name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # or 'main' or 'dev' depending on your setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install SnowSQL using official GitHub Action
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: '3.6.0'  # Optional: omit to use latest

      - name: Configure SnowSQL default connection
        run: |
          mkdir -p ~/.snowsql
          cat <<EOF > ~/.snowsql/config 
      [connections.default]
      accountname = ${ secrets.SNOWSQL_ACCOUNT }
      username = ${ secrets.SNOWSQL_USER }
      password = ${ secrets.SNOWSQL_PWD }
      rolename = ACCOUNTADMIN
      warehousename = DEVOPS_WH
      dbname = DEVOPS_DB
      schemaname = COMMON
      EOF
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}   
          

      - name: Run SQL using Snowflake CLI
        env:
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
          
        run: |
          snow sql -f snowflake-deploy.sql
