name: Deploy to Snowflake

on:
  push:
    branches:
      - main  # or 'dev' depending on your setup

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: '3.6.0'  # Optional: use latest if preferred

      - name: Set up SnowSQL config file
        env:
          SNOWSQL_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWSQL_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWSQL_PWD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          mkdir -p ~/.snowsql
          cat > ~/.snowsql/config <<EOF
          [connections.default]
          accountname = "${{ env.SNOWSQL_ACCOUNT }}"
          username = "${{ env.SNOWSQL_USER }}"
          password = "${{ env.SNOWSQL_PWD }}"
          rolename = ACCOUNTADMIN
          warehousename = DEVOPS_WH
          dbname = DEVOPS_DB
          schemaname = COMMON
          EOF

      - name: Run SQL using Snowflake CLI
        env:
          SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}
          SNOWFLAKE_USER: ${{ secrets.SNOWSQL_USER }}
          SNOWFLAKE_PASSWORD: ${{ secrets.SNOWSQL_PWD }}
        run: |
          snow sql --filename snowflake-deploy.sql
