name: Deploy to Snowflake

on:
  push:
    branches:
      - main  

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Snowflake CLI
        uses: snowflakedb/snowflake-cli-action@v1.5
        with:
          cli-version: '3.6.0'

      - name: Run SQL using Snowflake CLI with flags
        env:
          ACCOUNT: ${{ secrets.SNOWSQL_ACCOUNT }}         
          USER: ${{ secrets.SNOWSQL_USER }}              
          PASSWORD: ${{ secrets.SNOWSQL_PWD }}          
        run: |
          snow sql \
            -a $ACCOUNT \
            -u $USER \
            -p $PASSWORD \
            -r ACCOUNTADMIN \
            -w DEVOPS_WH \
            -d DEVOPS_DB \
            -s COMMON \
            --filename snowflake-deploy.sql

      - name: Run SQL using Snowflake CLI
        run: |
          snow sql --filename snowflake-deploy.sql --connection default
